# config/services.yaml

parameters:
    # Vous pouvez définir des paramètres ici si nécessaire

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Configuration des ressources pour l'autoloading des services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Repository\:
        resource: '../src/Repository'
        tags: ['repository.service']
        exclude: '../src/Repository/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
